#!/usr/bin/env tsx
/**
 * The six-document e-invoice matrix, generated BY THE APPLICATION (receivables services → posting →
 * e-invoice generation) on the local disposable database erp_finance_zatca, for validation with
 * ZATCA's official SDK. Synthetic identities only; LOCAL_ONLY profile; nothing is sent anywhere.
 *
 *   standard   (buyer with a VAT number):  invoice 388, credit note 381, debit note 383
 *   simplified (walk-in buyer):             invoice 388, credit note 381, debit note 383
 *
 * Content exercised: Arabic seller, buyer and line text; line discounts; prices with four decimals
 * that round at line level; standard-rated (S), zero-rated (Z) and exempt (E) lines on the standard
 * invoice. The exemption codes are SYNTHETIC TEST CHOICES (VATEX-SA-32 for the zero-rated line,
 * VATEX-SA-29 for the exempt line), not a company tax decision; their meaning must be confirmed
 * against the official code list.
 *
 * Writes to <outDir>: one directory per document with document.xml, qr.txt (base64 TLV), qr.bin and
 * meta.json (commit, fixture id, chain, hashes, local rule results, standards gaps), plus
 * MANIFEST.json and SHA256SUMS. Run through scripts/accounting/zatca-matrix.sh.
 */
import { checkUrl, assertDisposableFinanceDb } from "../finance/local-db-guard.mjs";
const DB = "erp_finance_zatca";
const problems = checkUrl(process.env.DATABASE_URL, DB);
if (problems.length) { console.error(`Refusing: ${problems.join("; ")}.`); process.exit(1); }
const OUT = process.argv[2];
if (!OUT) { console.error("usage: zatca-matrix.ts <outDir>"); process.exit(2); }

import { mkdirSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { execSync } from "node:child_process";
import { prisma } from "../../src/lib/db";
import { Prisma } from "../../src/generated/prisma/client";
import { applyChartTemplate, updateSettings } from "../../src/lib/accounting/setup-service";
import { createFiscalYear } from "../../src/lib/accounting/fiscal-period-service";
import { draftPolicy, approvePolicy } from "../../src/lib/accounting/policy-service";
import { createSalesDoc, submitSalesDoc, approveSalesDoc, postSalesDoc, type SalesLineInput } from "../../src/lib/accounting/receivables-service";
import * as EI from "../../src/lib/accounting/einvoice/service";
import { revalidate } from "../../src/lib/accounting/einvoice/service";
import { standardsGaps } from "../../src/lib/accounting/einvoice/rules";
import { QR_ENCODING, SIGNING_CURVE } from "../../src/lib/accounting/einvoice/ubl";
import { accountingDate, todayAccountingDate } from "../../src/lib/accounting/dates";

const FIXTURE_ID = "zatca-matrix-v1";
const sha256 = (b: Buffer | string) => createHash("sha256").update(b).digest("hex");
const dec = (s: string) => new Prisma.Decimal(s);
const TODAY = todayAccountingDate();
const YEAR = TODAY.getUTCFullYear();
const ISSUE = TODAY.toISOString().slice(0, 10);

async function user(username: string, name: string) {
  return (await prisma.employee.create({ data: { username, name, pin: "matrix-no-pin", role: "custom", permissions: "{}", preferredLanguage: "ar" } })).id;
}

async function main() {
  await assertDisposableFinanceDb({ url: process.env.DATABASE_URL, expectedDb: DB, query: (q: string) => prisma.$queryRawUnsafe(q) });
  if (await prisma.account.count()) { console.error("Refusing: the database is not freshly migrated (recreate it with zatca-matrix.sh)."); process.exit(1); }
  const commit = execSync("git rev-parse HEAD").toString().trim();
  // The output directory may sit inside the repository (evidence); it does not make the tree "dirty".
  const dirty = execSync(`git status --porcelain -- . ${JSON.stringify(`:(exclude)${OUT}`)}`).toString().trim() !== "";

  const prep = await user("matrix.preparer", "معدّ المصفوفة (تجريبي)");
  const appr = await user("matrix.approver", "معتمد المصفوفة (تجريبي)");
  await applyChartTemplate(prep);
  await createFiscalYear(YEAR, 1, prep);
  await updateSettings({ ledgerCutoverDate: accountingDate(`${YEAR}-01-01`), setupComplete: true }, prep);
  for (const key of ["receivables.recognition"]) { const p = await draftPolicy(key, {}, prep); await approvePolicy(p.id, appr); }
  const S = (await prisma.taxCategory.create({ data: { code: "MX-S15", nameEn: "Standard 15% (matrix)", nameAr: "قياسية ١٥٪", rate: dec("15.00"), isDefault: true, zatcaTaxCategoryCode: "S" } })).id;
  const Z = (await prisma.taxCategory.create({ data: { code: "MX-Z", nameEn: "Zero-rated export (matrix)", nameAr: "صفرية — تصدير", rate: dec("0"), categoryType: "ZERO_RATED", zatcaTaxCategoryCode: "Z", zatcaExemptionCode: "VATEX-SA-32", zatcaExemptionReason: "Export of goods (SYNTHETIC test choice)" } })).id;
  const E = (await prisma.taxCategory.create({ data: { code: "MX-E", nameEn: "Exempt (matrix)", nameAr: "معفاة", rate: dec("0"), categoryType: "EXEMPT", zatcaTaxCategoryCode: "E", zatcaExemptionCode: "VATEX-SA-29", zatcaExemptionReason: "Financial services (SYNTHETIC test choice)" } })).id;
  const b2b = (await prisma.customer.create({ data: { name: "Al-Waha Hotels (synthetic)", nameAr: "فنادق الواحة (بيانات تجريبية)", vatNumber: "300000000000003", crNumber: "1010010000",
    nationalAddress: { street: "طريق الملك فهد", buildingNo: "2468", district: "حي العليا", city: "الرياض", postalCode: "12211", countryCode: "SA" } } })).id;
  const b2c = (await prisma.customer.create({ data: { name: "Walk-in customer (synthetic)", nameAr: "عميل نقدي (تجريبي)" } })).id;
  const pf = await EI.draftProfile({ sellerName: "شركة حقبة للقهوة (بيانات تجريبية)", sellerNameEn: "Hiqbah Coffee (synthetic)", vatNumber: "399999999900003", crNumber: "1010000000",
    street: "شارع الأمير سلطان", buildingNo: "1234", district: "حي الروضة", city: "جدة", postalCode: "23435", countryCode: "SA", egsSerial: "EGS-MATRIX-01", environment: "LOCAL_ONLY" }, prep);
  await EI.approveProfile(pf.id, appr);

  const L = (description: string, quantity: string, unitPrice: string, taxCategoryId: string, discountPercent = "0"): SalesLineInput =>
    ({ description, quantity, unitPrice, discountPercent, taxCategoryId, stockTreatment: "NON_STOCK" } as SalesLineInput);
  const post = async (customerId: string, lines: SalesLineInput[], extra: Record<string, unknown> = {}) => {
    const d = await createSalesDoc({ customerId, issueDate: ISSUE, lines, ...extra } as never, prep);
    await submitSalesDoc(d.id, prep); await approveSalesDoc(d.id, appr);
    const r = await postSalesDoc(d.id, appr);
    if (r.einvoice?.status !== "GENERATED") throw new Error(`e-invoice not generated: ${JSON.stringify(r.einvoice)}`);
    return d.id;
  };

  const docs: { key: string; id: string }[] = [];
  // Standard (B2B).
  const sInv = await post(b2b, [
    L("بن عربي محمّص — كيس ١ كغ", "3", "33.3333", S, "10"),      // 3 × 33.3333 = 99.9999, less 10% → 90.00 (rounded)
    L("تدريب باريستا — جلسة", "1", "199.99", S),
    L("قهوة خضراء مصدّرة — شحنة", "2", "412.505", Z, "2.5"),       // zero-rated line with an exemption code
    L("رسوم خدمة مالية", "1", "15.75", E),                            // exempt line
  ]);
  docs.push({ key: "standard-invoice", id: sInv });
  docs.push({ key: "standard-credit-note", id: await post(b2b, [L("خصم سعر متفق عليه على البن", "1", "20.00", S)], { kind: "CREDIT_NOTE", originalInvoiceId: sInv, reason: "تعديل سعر متفق عليه (تجريبي)", creditType: "PRICE_ADJUSTMENT" }) });
  docs.push({ key: "standard-debit-note", id: await post(b2b, [L("رسوم توصيل إضافية", "1", "35.50", S)], { debitNoteOfId: sInv, reason: "رسوم توصيل لم تُفوتر (تجريبي)" }) });
  // Simplified (B2C).
  const cInv = await post(b2c, [
    L("قهوة مختصة — كوب", "7", "14.7826", S, "5"),
    L("حلوى تمر", "2", "9.99", S),
  ]);
  docs.push({ key: "simplified-invoice", id: cInv });
  docs.push({ key: "simplified-credit-note", id: await post(b2c, [L("خصم على كوب قهوة", "1", "4.35", S)], { kind: "CREDIT_NOTE", originalInvoiceId: cInv, reason: "تعديل سعر (تجريبي)", creditType: "PRICE_ADJUSTMENT" }) });
  docs.push({ key: "simplified-debit-note", id: await post(b2c, [L("إضافة كوب", "1", "14.7826", S)], { debitNoteOfId: cInv, reason: "صنف لم يُفوتر (تجريبي)" }) });

  mkdirSync(OUT, { recursive: true });
  const manifest = [];
  const sums: string[] = [];
  for (const { key, id } of docs) {
    const e = await prisma.eInvoice.findUniqueOrThrow({ where: { salesInvoiceId: id } });
    const dir = `${OUT}/${key}`; mkdirSync(dir, { recursive: true });
    const xml = Buffer.from(e.xml, "utf8");
    const qrBin = e.qr ? Buffer.from(e.qr, "base64") : Buffer.alloc(0);
    writeFileSync(`${dir}/document.xml`, xml);
    writeFileSync(`${dir}/qr.txt`, (e.qr ?? "") + "\n");
    writeFileSync(`${dir}/qr.bin`, qrBin);
    const rules = await revalidate(e.id);
    const meta = { key, commit, workingTreeDirty: dirty, fixture: FIXTURE_ID, salesInvoiceId: id, eInvoiceId: e.id, typeCode: e.typeCode, subtype: e.subtype, icv: e.icv, uuid: e.uuid,
      invoiceHash: e.invoiceHash, previousHash: e.previousHash, signer: e.signer, qrEncoding: QR_ENCODING, signingCurve: SIGNING_CURVE,
      sha256: { xml: sha256(xml), qrBase64: sha256(e.qr ?? ""), qrBinary: sha256(qrBin) },
      localRules: { total: rules.length, failed: rules.filter((r) => !r.ok).map((r) => r.id) }, standardsGaps: standardsGaps(e.subtype, e.qr).map((g) => g.id),
      officialValidation: "NOT RUN — see ZATCA_REQUIREMENTS.md" };
    writeFileSync(`${dir}/meta.json`, JSON.stringify(meta, null, 2) + "\n");
    manifest.push(meta);
    for (const f of ["document.xml", "qr.txt", "qr.bin", "meta.json"]) sums.push(`${sha256(await import("node:fs").then((m) => m.readFileSync(`${dir}/${f}`)))}  ${key}/${f}`);
    console.log(`${key}: ${e.typeCode}/${e.subtype} ICV ${e.icv} xml ${meta.sha256.xml.slice(0, 12)} local rules failed: ${meta.localRules.failed.join(",") || "none"}`);
  }
  writeFileSync(`${OUT}/MANIFEST.json`, JSON.stringify({ fixture: FIXTURE_ID, commit, workingTreeDirty: dirty, generatedAt: new Date().toISOString(), documents: manifest }, null, 2) + "\n");
  writeFileSync(`${OUT}/SHA256SUMS`, sums.join("\n") + "\n");
}
main().then(async () => { await prisma.$disconnect(); process.exit(0); }).catch(async (e) => { console.error(e instanceof Error ? e.message : e); await prisma.$disconnect(); process.exit(1); });
