// D1 — confirmed outgoing commitments reduce cash available for new allocation before bank
// settlement, and each economic payment reduces it exactly once across its representations:
// payment request (reservation) → recorded payment → pending bank line → settled bank line.
// Run: npm run test:finance:db. With FIN_EVIDENCE_FILE set, every step's balances are written
// there as Markdown tables (docs/finance/evidence/d1-balances.md).
import { test, describe, beforeEach, after } from "node:test";
import assert from "node:assert/strict";
import { appendFileSync, writeFileSync } from "node:fs";
import { prisma, reset, makeUser, ALL_SCOPE_SUBS, APPROVER_SUBS } from "./support";
import { resolveScope, COMPANY } from "../../../src/lib/finance/server/context";
import { createAccount, createManualTransaction, reviewTransaction, commitImport, voidTransaction } from "../../../src/lib/finance/server/transactions";
import { createCategory, manualAllocate, createReservation, executeReservation, releaseReservation, listCategories } from "../../../src/lib/finance/server/allocation";
import { decideApproval } from "../../../src/lib/finance/server/approvals";
import { installRecommended } from "../../../src/lib/finance/server/setup";
import { poolSummaries } from "../../../src/lib/finance/server/ledger";
import { riyadhDateString, monthOf, monthStart } from "../../../src/lib/finance/dates";
import { fromMinor } from "../../../src/lib/finance/money";

const today = riyadhDateString();
const d1 = monthStart(monthOf(today));
const mapping = { date: "Date", amount: "Amount", reference: "Reference", description: "Description", dateFormat: "YYYY-MM-DD" };
const EVIDENCE = process.env.FIN_EVIDENCE_FILE;
let evidenceStarted = false;

async function setup() {
  const prep = await makeUser("Preparer", ALL_SCOPE_SUBS);
  const appr = await makeUser("Approver", APPROVER_SUBS);
  const ps = await resolveScope(prep);
  await installRecommended(prep, ps, COMPANY);
  const bank = await createAccount(prep, ps, { code: "BANK1", nameEn: "Main bank", openingBalance: "10000", openingBalanceDate: d1 });
  const g = await createCategory(prep, ps, { code: "GREEN", nameEn: "Green coffee", spendingLimit: "3000", approverEmployeeId: appr.id });
  const other = await createCategory(prep, ps, { code: "OTHER", nameEn: "Other" });
  await manualAllocate(prep, ps, { categoryId: g.id, amount: "5000", sourceCashAccountId: bank.id, reason: "fund green coffee" });
  return { prep, appr, ps, as: await resolveScope(appr), bank, g, other };
}
type Ctx = Awaited<ReturnType<typeof setup>>;

type Row = { step: string; book: number; eligible: number; reserved: number; allocated: number; available: number; catBalance: number; catAvailable: number; lines: number };
async function balances(c: Ctx, step: string): Promise<Row> {
  const p = (await poolSummaries(prisma, c.ps)).find((x) => x.branchKey === COMPANY)!;
  assert.equal(p.allocated + p.unallocated, p.eligibleCash, `${step}: allocated + available = eligible cash`);
  const g = (await listCategories(prisma, c.ps)).find((x) => x.id === c.g.id)!;
  return { step, book: p.bookCash, eligible: p.eligibleCash, reserved: p.reserved, allocated: p.allocated, available: p.unallocated, catBalance: g.balance, catAvailable: g.available, lines: await prisma.bankTransaction.count({ where: { status: { not: "VOID" } } }) };
}
function record(title: string, rows: Row[]) {
  if (!EVIDENCE) return;
  if (!evidenceStarted) { writeFileSync(EVIDENCE, "# D1 — balances at each step (SAR)\n\nGenerated by `tests/finance/integration/exactly-once.test.ts` on the disposable test database. Opening bank balance 10,000.00; GREEN funded with 5,000.00 (limit 3,000.00).\n\n**Cash** = book cash · **Eligible** = cash counted for allocation · **Reserved** = open payment requests · **Allocated** = held back from new allocation (Σ max(balance, approved requests, 0)) · **Available** = eligible − allocated.\n"); evidenceStarted = true; }
  const m = (n: number) => fromMinor(n);
  appendFileSync(EVIDENCE, `\n## ${title}\n\n| Step | Cash | Eligible | Reserved | Allocated | Available | GREEN balance | GREEN available | Bank lines |\n|---|---:|---:|---:|---:|---:|---:|---:|---:|\n` +
    rows.map((r) => `| ${r.step} | ${m(r.book)} | ${m(r.eligible)} | ${m(r.reserved)} | ${m(r.allocated)} | ${m(r.available)} | ${m(r.catBalance)} | ${m(r.catAvailable)} | ${r.lines} |`).join("\n") + "\n");
}
async function approvedRequest(c: Ctx, amount: string) {
  const r = await createReservation(c.prep, c.ps, { categoryId: c.g.id, amount, payee: "Andes Coffee", purpose: "Huila lot" });
  const req = await prisma.finApprovalRequest.findFirstOrThrow({ where: { entityId: r.reservation.id } });
  return { r: r.reservation, req };
}

beforeEach(reset);
after(async () => { await prisma.$disconnect(); });

describe("D1 exactly-once cash protection", () => {
  test("request → recorded payment → pending bank line → settled line → duplicate import: available falls once", async () => {
    const c = await setup();
    const rows: Row[] = [await balances(c, "GREEN funded 5,000")];
    const { r, req } = await approvedRequest(c, "6000");
    rows.push(await balances(c, "Request 6,000 held for override (not yet a commitment)"));
    assert.equal(rows[1].available, rows[0].available, "an unapproved request is not a commitment");
    await decideApproval(c.appr, c.as, req.id, { decision: "APPROVE" });
    rows.push(await balances(c, "Override approved: commitment 6,000 > balance 5,000"));
    assert.equal(rows[2].available, 400_000, "the approved commitment reduces availability before any bank movement");
    const line = (await createManualTransaction(c.prep, c.ps, { cashAccountId: c.bank.id, amount: "-6000", txnDate: today, status: "PENDING", bankReference: "TRF-601", description: "Andes Coffee transfer" })).transaction;
    rows.push(await balances(c, "Transfer made in online banking, entered as pending line (not yet linked)"));
    await executeReservation(c.prep, c.ps, r.id, { txnId: line.id });
    rows.push(await balances(c, "Record payment made (request ↔ line linked)"));
    await commitImport(c.prep, c.ps, { cashAccountId: c.bank.id, csv: `Date,Amount,Reference,Description\n${today},-6000.00,TRF-601,OUTWARD TRF\n`, mapping, importAsPending: true });
    rows.push(await balances(c, "Bank feed shows the transfer as pending (attached, no new line)"));
    const settled = await commitImport(c.prep, c.ps, { cashAccountId: c.bank.id, csv: `Date,Amount,Reference,Description\n${today},-6000.00,TRF-601,OUTWARD TRF\n`, mapping });
    assert.equal(settled.attachedCount, 1, "the settled row confirms the pending line");
    assert.equal((await prisma.bankTransaction.findUniqueOrThrow({ where: { id: line.id } })).status, "CONFIRMED");
    rows.push(await balances(c, "Statement shows it settled (pending → confirmed)"));
    const dup = await commitImport(c.prep, c.ps, { cashAccountId: c.bank.id, csv: `Date,Amount,Reference,Description\n${today},-6000.00,TRF-601,OUTWARD TRF\n`, mapping });
    assert.equal(dup.importedCount + dup.attachedCount, 0);
    rows.push(await balances(c, "Same statement imported again"));
    record("1. One payment through every representation", rows);
    for (const row of rows.slice(2)) assert.equal(row.available, 400_000, `${row.step}: available unchanged — the payment counted once`);
    assert.equal(rows.at(-1)!.book, 1_000_000 - 600_000);
    assert.equal(rows.at(-1)!.lines, 1, "one bank line for one payment");
    assert.equal(await prisma.allocationEntry.count({ where: { entryType: "PAYMENT" } }), 1);
  });

  test("bank feed first: an imported pending line for the request's amount counts once before it is linked", async () => {
    const c = await setup();
    const { r, req } = await approvedRequest(c, "6000");
    await decideApproval(c.appr, c.as, req.id, { decision: "APPROVE" });
    const rows: Row[] = [await balances(c, "Override approved")];
    await commitImport(c.prep, c.ps, { cashAccountId: c.bank.id, csv: `Date,Amount,Reference,Description\n${today},-6000.00,TRF-777,OUTWARD TRF\n`, mapping, importAsPending: true });
    rows.push(await balances(c, "Feed imports the pending transfer (unlinked, unreviewed)"));
    const p = (await poolSummaries(prisma, c.ps)).find((x) => x.branchKey === COMPANY)!;
    assert.equal(p.unlinkedPayments.length, 1, "reported: matches an approved request, awaiting Record payment made");
    const line = await prisma.bankTransaction.findFirstOrThrow({ where: { bankReference: "TRF-777" } });
    await executeReservation(c.prep, c.ps, r.id, { txnId: line.id });
    rows.push(await balances(c, "Record payment made against the imported line"));
    await commitImport(c.prep, c.ps, { cashAccountId: c.bank.id, csv: `Date,Amount,Reference,Description\n${today},-6000.00,TRF-777,OUTWARD TRF\n`, mapping });
    rows.push(await balances(c, "Settled"));
    record("2. Bank feed before the payment is recorded", rows);
    for (const row of rows) assert.equal(row.available, 400_000, `${row.step}: once`);
  });

  test("cancellation and failure restore availability only when the commitment is actually released", async () => {
    const c = await setup();
    const rows: Row[] = [await balances(c, "GREEN funded 5,000")];
    // a) approved, then released before paying.
    const a = await approvedRequest(c, "6000");
    await decideApproval(c.appr, c.as, a.req.id, { decision: "APPROVE" });
    rows.push(await balances(c, "a) request approved"));
    await releaseReservation(c.prep, c.ps, a.r.id, "supplier cancelled");
    rows.push(await balances(c, "a) request released → commitment gone"));
    assert.equal(rows[2].available, rows[0].available);
    // b) paid, then the transfer failed: void the line → commitment stands again; release → restored.
    const b = await approvedRequest(c, "6000");
    await decideApproval(c.appr, c.as, b.req.id, { decision: "APPROVE" });
    const line = (await createManualTransaction(c.prep, c.ps, { cashAccountId: c.bank.id, amount: "-6000", txnDate: today, status: "PENDING", bankReference: "TRF-900", description: "transfer" })).transaction;
    await executeReservation(c.prep, c.ps, b.r.id, { txnId: line.id });
    rows.push(await balances(c, "b) request approved and payment recorded"));
    await voidTransaction(c.prep, c.ps, line.id, "bank rejected the transfer");
    rows.push(await balances(c, "b) transfer failed → line voided (request reopened, still owed)"));
    assert.equal(rows[4].available, rows[3].available, "a failed payment does not free the committed cash");
    assert.equal((await prisma.paymentReservation.findUniqueOrThrow({ where: { id: b.r.id } })).status, "ACTIVE");
    await releaseReservation(c.prep, c.ps, b.r.id, "order cancelled");
    rows.push(await balances(c, "b) request released → restored"));
    assert.equal(rows[5].available, rows[0].available);
    // c) an override that is rejected was never a commitment.
    const d = await approvedRequest(c, "6000");
    rows.push(await balances(c, "c) request held for override"));
    await decideApproval(c.appr, c.as, d.req.id, { decision: "REJECT", note: "not this month" });
    rows.push(await balances(c, "c) override rejected"));
    assert.equal(rows[6].available, rows[0].available);
    assert.equal(rows[7].available, rows[0].available);
    record("3. Cancellation and failure", rows);
  });

  test("an unmatched imported pending outflow is routed for review, then counted once", async () => {
    const c = await setup();
    const rows: Row[] = [await balances(c, "GREEN funded 5,000")];
    await commitImport(c.prep, c.ps, { cashAccountId: c.bank.id, csv: `Date,Amount,Reference,Description\n${today},-450.00,POS-77,CARD PURCHASE PENDING\n`, mapping, importAsPending: true });
    rows.push(await balances(c, "Feed imports an unknown pending card purchase −450"));
    const p = (await poolSummaries(prisma, c.ps)).find((x) => x.branchKey === COMPANY)!;
    assert.equal(p.pendingOutAwaitingReview, 45_000, "shown as awaiting review");
    assert.equal(rows[1].available, rows[0].available, "not deducted until someone confirms it");
    const l = await prisma.bankTransaction.findFirstOrThrow({ where: { bankReference: "POS-77" } });
    assert.equal(l.reviewStatus, "NEEDS_REVIEW", "it sits in the review queue");
    const fin = Object.fromEntries((await prisma.finCategory.findMany()).map((x) => [x.code, x.id]));
    await reviewTransaction(c.prep, c.ps, l.id, { classification: "OTHER_OPERATING_PAYMENT", splits: [{ finCategoryId: fin["PY-OTHER"] ?? Object.values(fin)[0], amount: "-450" }] });
    rows.push(await balances(c, "Reviewer confirms it is a real payment"));
    assert.equal(rows[2].available, rows[0].available - 45_000, "counted once, after review");
    await commitImport(c.prep, c.ps, { cashAccountId: c.bank.id, csv: `Date,Amount,Reference,Description\n${today},-450.00,POS-77,CARD PURCHASE PENDING\n`, mapping });
    rows.push(await balances(c, "It settles"));
    assert.equal(rows[3].available, rows[2].available);
    record("4. Unmatched pending outflow", rows);
  });

  test("concurrent requests: one line pays one request, a request is paid once, allocations never exceed what is available", async () => {
    const c = await setup();
    const rows: Row[] = [await balances(c, "GREEN funded 5,000")];
    // Two requests of 2,000 (within limit and balance, no override needed) → both ACTIVE.
    const x = await createReservation(c.prep, c.ps, { categoryId: c.g.id, amount: "2000", payee: "A", purpose: "x" });
    const y = await createReservation(c.prep, c.ps, { categoryId: c.g.id, amount: "2000", payee: "B", purpose: "y" });
    assert.equal(x.reservation.status, "ACTIVE");
    assert.equal(y.reservation.status, "ACTIVE");
    rows.push(await balances(c, "Two requests of 2,000 (inside the 5,000 balance)"));
    const line = (await createManualTransaction(c.prep, c.ps, { cashAccountId: c.bank.id, amount: "-2000", txnDate: today, status: "PENDING", bankReference: "TRF-1", description: "one transfer" })).transaction;
    rows.push(await balances(c, "One 2,000 transfer entered (unlinked)"));
    const race = await Promise.allSettled([executeReservation(c.prep, c.ps, x.reservation.id, { txnId: line.id }), executeReservation(c.prep, c.ps, y.reservation.id, { txnId: line.id })]);
    assert.equal(race.filter((r) => r.status === "fulfilled").length, 1, "one 2,000 line cannot pay two 2,000 requests");
    rows.push(await balances(c, "Both requests race to claim the line → one wins"));
    const open = (await prisma.paymentReservation.findFirstOrThrow({ where: { id: { in: [x.reservation.id, y.reservation.id] }, status: "ACTIVE" } })).id;
    const l2 = (await createManualTransaction(c.prep, c.ps, { cashAccountId: c.bank.id, amount: "-2000", txnDate: today, status: "PENDING", bankReference: "TRF-2", description: "second transfer" })).transaction;
    rows.push(await balances(c, "Second 2,000 transfer entered (matches the open request)"));
    const l3 = (await createManualTransaction(c.prep, c.ps, { cashAccountId: c.bank.id, amount: "-2000", txnDate: today, status: "PENDING", bankReference: "TRF-3", description: "entered twice by mistake" })).transaction;
    const race2 = await Promise.allSettled([executeReservation(c.prep, c.ps, open, { txnId: l2.id }), executeReservation(c.prep, c.ps, open, { txnId: l3.id })]);
    assert.equal(race2.filter((r) => r.status === "fulfilled").length, 1, "one request is paid once");
    const loser = race2[0].status === "fulfilled" ? l3.id : l2.id;
    await voidTransaction(c.prep, c.ps, loser, "entered twice by mistake");
    rows.push(await balances(c, "The same request raced with two lines → one wins; the extra entry is voided"));
    assert.equal(rows.at(-1)!.available, rows[1].available, "two payments of two requests: availability as when they were committed");
    // Four concurrent allocations of more than half the room: at most one fits.
    const room = rows.at(-1)!.available;
    const part = fromMinor(Math.floor(room / 2) + 100);
    const race3 = await Promise.allSettled(Array.from({ length: 4 }, () => manualAllocate(c.prep, c.ps, { categoryId: c.other.id, amount: part, sourceCashAccountId: c.bank.id, reason: "race" })));
    assert.equal(race3.filter((r) => r.status === "fulfilled").length, 1);
    rows.push(await balances(c, `Four concurrent allocations of ${part} → one succeeds`));
    assert.ok(rows.at(-1)!.available >= 0);
    record("5. Concurrent requests", rows);
  });
});
